[package]
authors = ["maxcabd <max.cabd@gmail.com>"]
description = "A tool to unpack Eighting .mot files"
name = "mot_unpack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.10.0"
